$discovery=<<SCRIPT
#!/bin/bash
set -xe
apt-get update -y
apt-get install curl -y
cd /tmp
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
systemctl enable --now docker
docker run --restart always --name vault \
-d --net=host --cap-add=IPC_LOCK vault:1.2.3 vault server -dev \
-dev-listen-address=192.168.33.10:8200 \
-dev-root-token-id=toor
export VAULT_ADDR=http://192.168.33.10:8200
export VAULT_TOKEN=toor
SCRIPT

Vagrant.configure(2) do |config|
    config.vm.define "discovery" do |discovery|
        discovery.vm.box = "ubuntu/bionic64"
        discovery.vm.hostname = "discovery"
        discovery.vm.network :private_network, ip: "192.168.33.10"
        discovery.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
        discovery.vm.provision :shell, inline: $discovery
    end
end
