before:
  hooks:
  - go mod tidy
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
builds:
- id: "k8s-kms-plugin"
  main: ./cmd/k8s-kms-plugin
  binary: k8s-kms-plugin
  ldflags:
  - '--extldflags "-static"'
  flags:
  - -a
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
